controller_manager:
  ros__parameters:
    update_rate: 30

    ackermann_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

ackermann_cont:
  ros__parameters:
    traction_joints_names: ['rear_left_wheel_joint', 'rear_right_wheel_joint']
    steering_joints_names: ['front_left_wheel_joint', 'front_right_wheel_joint']
    wheelbase: 2.61688
    front_track: 1.773604
    rear_track: 1.773604
    traction_wheels_radius: 0.05
    position_feedback: false
    open_loop: true
